version: '2.4'

services:

  # Create NMOS Registry/Controller container instance
  nmos-crosspoint:
    build: 
      context: './'
    container_name: nmos-crosspoint_v2
    hostname: nmos-crosspoint_v2
    domainname: local
    network_mode: host
    volumes:
    - nmos-state:/nmos-crosspoint/server/state
    # Added depends_on for startup order (optional but good practice)
    depends_on:
      - nmos-registry
    restart: unless-stopped # Added restart policy

  nmos-registry:
    # image: rhastie/nmos-cpp:latest
    # image: nvcr.io/nvidia/holoscan-for-media/nmos-cpp:0.4.0
    build:
      context: .
      dockerfile: Dockerfile.registry
    container_name: nmos-registry
    hostname: nmos-registry
    privileged: true # Added based on rhastie/nmos-cpp documentation
    network_mode: host
    restart: unless-stopped # Added restart policy
    environment:
      - RUN_NODE=FALSE
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    # No volumes needed for basic registry operation
    labels:
      io.balena.features.dbus: '1'
    
  # ZeroTier gateway service
  zerotier:
    build:
      context: ./
      dockerfile: Dockerfile.zerotier.template
    privileged: true
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - NET_RAW
    volumes:
      - zerotier-data:/var/lib/zerotier-one
    restart: unless-stopped
    labels:
      io.balena.features.dbus: '1'
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

volumes:
  nmos-state:
  zerotier-data:
